#!/usr/bin/env python3
"""Validate V2's narrow amendment and generate its Lean projection."""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
DEFAULT_INPUT = REPO / "fixtures/requirements/broadcast_add_prospective_v2_amendment.json"
DEFAULT_OUTPUT = REPO / "Tgrad/Growth/BroadcastAddManifestV2Generated.lean"
EXPECTED_MUTATIONS = (
    "MUT-ADD-WRONG-RIGHT-ALIGNMENT",
    "MUT-ADD-NO-SINGLETON-EXPANSION",
)


def canonical(value: object) -> bytes:
    return json.dumps(value, sort_keys=True, separators=(",", ":")).encode()


def digest(raw: bytes) -> str:
    return hashlib.sha256(raw).hexdigest()


def parse(path: Path) -> tuple[dict, str, str]:
    raw = path.read_bytes()
    document = json.loads(raw)
    if document.get("schema_version") != 1:
        raise RuntimeError("unsupported V2 amendment schema")
    base_path = REPO / document.get("base_manifest_path", "")
    lock_path = REPO / document.get("supersedes_trial_lock_path", "")
    if not base_path.is_file() or digest(base_path.read_bytes()) != document.get("base_manifest_sha256"):
        raise RuntimeError("V2 amendment does not bind the exact V1 manifest")
    if not lock_path.is_file() or digest(lock_path.read_bytes()) != document.get("supersedes_trial_lock_sha256"):
        raise RuntimeError("V2 amendment does not bind the exact V1 trial lock")
    if document.get("v1_disposition") != "definition_refuted_before_observation":
        raise RuntimeError("V1 disposition must remain explicit")
    if document.get("all_other_definition_fields_inherited_unchanged") is not True:
        raise RuntimeError("V2 must inherit every unamended definition field")
    if document.get("frozen_before_observer_implementation") is not True:
        raise RuntimeError("V2 is not prospective with respect to its observer")
    if document.get("frozen_before_product_candidate") is not True:
        raise RuntimeError("V2 is not prospective with respect to product work")
    amendments = document.get("amendments")
    if not isinstance(amendments, list) or len(amendments) != 2:
        raise RuntimeError("V2 must contain exactly two narrow amendments")
    ids = tuple(item.get("mutation_id") for item in amendments)
    if ids != EXPECTED_MUTATIONS:
        raise RuntimeError("V2 amendment mutation ids or order changed")
    for item in amendments:
        if item != {
            "mutation_id": item["mutation_id"], "dimension": "dtype",
            "from": "must_not_change", "to": "may_be_unobserved",
        }:
            raise RuntimeError("V2 amendment changes more than dtype observability")
    amendment_hash = digest(raw)
    effective_hash = digest(canonical({
        "base_manifest_sha256": document["base_manifest_sha256"],
        "amendment_sha256": amendment_hash,
    }))
    return document, amendment_hash, effective_hash


def q(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def generated(path: Path, document: dict, amendment_hash: str,
              effective_hash: str) -> str:
    relative = path.relative_to(REPO).as_posix()
    ids = ", ".join(q(item) for item in EXPECTED_MUTATIONS)
    return f'''import Tgrad.Growth.BroadcastAddManifestGenerated

/- GENERATED by scripts/spec/generate_broadcast_add_amendment_v2.py; do not edit. -/

namespace Tgrad.Growth.BroadcastAddManifestV2Generated

def trialId : String := {q(document["trial_id"])}
def packetId : String := {q(document["packet_id"])}
def baselineRevision : String := {q(document["baseline_revision"])}
def amendmentPath : String := {q(relative)}
def amendmentHash : String := {q(amendment_hash)}
def baseManifestHash : String := {q(document["base_manifest_sha256"])}
def supersededLockHash : String := {q(document["supersedes_trial_lock_sha256"])}
def effectiveManifestHash : String := {q(effective_hash)}
def amendedMutationIds : List String := [{ids}]

theorem amendment_has_exactly_two_mutations : amendedMutationIds.length = 2 := by decide

end Tgrad.Growth.BroadcastAddManifestV2Generated
'''


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    source = args.input.resolve()
    document, amendment_hash, effective_hash = parse(source)
    output = generated(source, document, amendment_hash, effective_hash)
    target = args.output.resolve()
    if args.check:
        if not target.is_file() or target.read_text(encoding="utf-8") != output:
            raise RuntimeError(f"generated V2 amendment is stale: {target}")
        print(f"checked {target}")
        return 0
    target.parent.mkdir(parents=True, exist_ok=True)
    fd, raw_temp = tempfile.mkstemp(prefix=f".{target.name}.", dir=target.parent)
    temp = Path(raw_temp)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(output)
        os.replace(temp, target)
    except BaseException:
        temp.unlink(missing_ok=True)
        raise
    print(f"wrote {target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
