#!/usr/bin/env python3
"""Validate V3's narrow trace-footprint amendment and generate its Lean projection."""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
DEFAULT_INPUT = REPO / "fixtures/requirements/broadcast_add_prospective_v3_amendment.json"
DEFAULT_OUTPUT = REPO / "Tgrad/Growth/BroadcastAddManifestV3Generated.lean"
EXPECTED = (
    (
        "MUT-ADD-WRONG-RIGHT-ALIGNMENT",
        ("invoke_add", "capture_result_identity", "observe_shape", "observe_dtype",
         "realize_1", "readback_1", "realize_2", "readback_2", "snapshot_inputs_after"),
        ("observe_shape", "observe_dtype", "realize_1", "readback_1", "realize_2",
         "readback_2", "snapshot_inputs_after"),
    ),
    (
        "MUT-ADD-ACCEPT-INCOMPATIBLE",
        ("invoke_add", "observe_shape_if_constructed"),
        ("observe_shape_if_constructed",),
    ),
)


def canonical(value: object) -> bytes:
    return json.dumps(value, sort_keys=True, separators=(",", ":")).encode()


def digest(raw: bytes) -> str:
    return hashlib.sha256(raw).hexdigest()


def parse(path: Path) -> tuple[dict, str, str]:
    raw = path.read_bytes()
    document = json.loads(raw)
    if document.get("schema_version") != 1:
        raise RuntimeError("unsupported V3 amendment schema")
    bindings = (
        ("base_v2_amendment_path", "base_v2_amendment_sha256"),
        ("base_v2_lock_path", "base_v2_lock_sha256"),
        ("v2_observer_path", "v2_observer_sha256"),
    )
    for path_key, hash_key in bindings:
        bound = REPO / document.get(path_key, "")
        if not bound.is_file() or digest(bound.read_bytes()) != document.get(hash_key):
            raise RuntimeError(f"V3 amendment does not bind exact {path_key}")
    diagnostic = (
        REPO / "fixtures/requirements/observations" /
        document.get("refuting_evidence_id", "") / "diagnostic.json"
    )
    if not diagnostic.is_file() or digest(diagnostic.read_bytes()) != document.get(
        "refuting_diagnostic_sha256"
    ):
        raise RuntimeError("V3 amendment does not bind its refuting diagnostic")
    diagnostic_document = json.loads(diagnostic.read_text(encoding="utf-8"))
    if diagnostic_document.get("evidence_id") != document.get("refuting_evidence_id") or \
            diagnostic_document.get("result_kind") != "diagnostic_blocker" or \
            diagnostic_document.get("inference_policy", {}).get("baseline_eligible") is not False:
        raise RuntimeError("V3 refutation is not an ineligible diagnostic blocker")
    if document.get("v2_disposition") != \
            "calibration_contract_refuted_by_pinned_upstream_observation":
        raise RuntimeError("V2 disposition must remain explicit")
    required_true = (
        "all_requirements_scenarios_dimensions_mutants_and_other_footprints_inherited_unchanged",
        "frozen_before_v3_observer_implementation",
        "frozen_before_product_candidate",
        "diagnostic_is_not_baseline_evidence",
    )
    if any(document.get(key) is not True for key in required_true):
        raise RuntimeError("V3 amendment weakens chronology or inheritance")
    amendments = document.get("trace_footprint_amendments")
    actual = tuple(
        (item.get("mutation_id"), tuple(item.get("from", [])), tuple(item.get("to", [])))
        for item in amendments or []
    )
    if actual != EXPECTED:
        raise RuntimeError("V3 must contain exactly the two observed trace-footprint corrections")
    amendment_hash = digest(raw)
    effective_hash = digest(canonical({
        "base_v2_amendment_sha256": document["base_v2_amendment_sha256"],
        "base_v2_lock_sha256": document["base_v2_lock_sha256"],
        "v2_observer_sha256": document["v2_observer_sha256"],
        "v3_amendment_sha256": amendment_hash,
    }))
    return document, amendment_hash, effective_hash


def q(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def lean_list(values: tuple[str, ...]) -> str:
    return "[" + ", ".join(q(value) for value in values) + "]"


def generated(path: Path, document: dict, amendment_hash: str, effective_hash: str) -> str:
    relative = path.relative_to(REPO).as_posix()
    rows = ",\n  ".join(
        "{ mutationId := " + q(mutation) + ", before := " + lean_list(before) +
        ", after := " + lean_list(after) + " }"
        for mutation, before, after in EXPECTED
    )
    return f'''import Tgrad.Growth.BroadcastAddManifestV2

/- GENERATED by scripts/spec/generate_broadcast_add_amendment_v3.py; do not edit. -/

namespace Tgrad.Growth.BroadcastAddManifestV3Generated

structure TraceFootprintAmendment where
  mutationId : String
  before : List String
  after : List String
  deriving DecidableEq, BEq, Repr, Inhabited

def trialId : String := {q(document["trial_id"])}
def packetId : String := {q(document["packet_id"])}
def baselineRevision : String := {q(document["baseline_revision"])}
def amendmentPath : String := {q(relative)}
def amendmentHash : String := {q(amendment_hash)}
def baseV2LockHash : String := {q(document["base_v2_lock_sha256"])}
def v2ObserverHash : String := {q(document["v2_observer_sha256"])}
def refutingEvidenceId : String := {q(document["refuting_evidence_id"])}
def effectiveContractHash : String := {q(effective_hash)}
def traceAmendments : List TraceFootprintAmendment := [
  {rows}]

theorem amendment_has_exactly_two_trace_corrections : traceAmendments.length = 2 := by decide

end Tgrad.Growth.BroadcastAddManifestV3Generated
'''


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    source = args.input.resolve()
    document, amendment_hash, effective_hash = parse(source)
    output = generated(source, document, amendment_hash, effective_hash)
    target = args.output.resolve()
    if args.check:
        if not target.is_file() or target.read_text(encoding="utf-8") != output:
            raise RuntimeError(f"generated V3 amendment is stale: {target}")
        print(f"checked {target}")
        return 0
    target.parent.mkdir(parents=True, exist_ok=True)
    descriptor, raw_temp = tempfile.mkstemp(prefix=f".{target.name}.", dir=target.parent)
    temporary = Path(raw_temp)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
            handle.write(output)
        os.replace(temporary, target)
    except BaseException:
        temporary.unlink(missing_ok=True)
        raise
    print(f"wrote {target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
