/*
 * tgrad_python.c — Python → Lean FFI trampolines for Tgrad's matmul layer.
 *
 * Lean owns the matmul / alloc / dispatch path (see Tgrad/PythonFFI.lean's
 * @[export] entries). This file is the bridge that translates Python's
 * ctypes calling convention to Lean's IO / ByteArray calling convention.
 *
 * Pairs with tgrad_init() — initializes the Lean runtime once at module
 * load. Subsequent calls into Lean from Python go through these
 * trampolines.
 *
 * Companion file: python/tgrad.py uses ctypes.CDLL to load
 * libtgrad.dylib (which links this file + the Lean module .o files +
 * Apple's Metal frameworks).
 */
#include <lean/lean.h>
#include <stdbool.h>
#include <stdint.h>
#include <stddef.h>
#include <string.h>

/* lean_initialize is exported by libleanshared but not declared in
 * lean.h's public header. Mirror Lake's generated executable wrapper. */
extern void lean_initialize(void);

/* Lean's runtime + task-manager init. lean_initialize / lean_set_panic_messages
 * / lean_init_task_manager are declared in lean/lean.h (LEAN_EXPORT). */

/* The Lean module initializer for Tgrad. Generated by Lake. */
extern lean_object* initialize_tgrad_Tgrad(uint8_t builtin);

/* @[export] entries declared in Tgrad/PythonFFI.lean. */
extern lean_object* tgrad_tensor_alloc_lean(size_t n_bytes);
extern lean_object* tgrad_tensor_free_lean(uint64_t buf_ptr, size_t n_bytes);
extern lean_object* tgrad_tensor_write_bytes_lean(uint64_t buf_ptr, lean_object* bytes);
extern lean_object* tgrad_tensor_read_bytes_lean(uint64_t buf_ptr, size_t n_bytes);
extern lean_object* tgrad_matmul_64x64_lean(uint64_t a, uint64_t b, uint64_t out);
extern lean_object* tgrad_dtype_query_lean(uint8_t code, uint8_t query);
extern lean_object* tgrad_dtype_binary_query_lean(uint8_t query, uint8_t left, uint8_t right);
extern lean_object* tgrad_dtype_unary_query_lean(uint8_t query, uint8_t code);
extern lean_object* tgrad_dtype_lub_many_lean(lean_object* codes);
extern lean_object* tgrad_dtype_infer_python_lean(lean_object* tags);
extern lean_object* tgrad_dtype_default_lean(uint8_t which);
extern lean_object* tgrad_dtype_set_default_lean(uint8_t which, uint8_t code);
extern lean_object* tgrad_dtype_creation_default_lean(void);
extern lean_object* tgrad_dtype_backend_name_lean(uint8_t code);
extern lean_object* tgrad_dtype_public_name_lean(uint8_t code);
extern lean_object* tgrad_dtype_display_name_lean(uint8_t code);
extern lean_object* tgrad_creation_shape_admission_lean(lean_object* shape);
extern lean_object* tgrad_creation_dtype_resolve_lean(
    uint8_t fill_tag, uint8_t dtype_code);
extern lean_object* tgrad_full_like_query_lean(
    uint64_t source_handle, uint8_t fill_tag, uint8_t dtype_code,
    uint8_t query, size_t index);
extern lean_object* tgrad_tensor_full_like_lean(
    uint64_t source_handle, double fill, uint8_t fill_tag,
    uint8_t dtype_code);
extern lean_object* tgrad_range_query_lean(
    lean_object* start_int, lean_object* stop_int, lean_object* step_int,
    double start_float, double stop_float, double step_float,
    uint8_t start_tag, uint8_t stop_tag, uint8_t step_tag,
    uint8_t has_stop, uint8_t dtype_code, uint8_t query, size_t index);
extern lean_object* tgrad_tensor_arange_lean(
    lean_object* start_int, lean_object* stop_int, lean_object* step_int,
    double start_float, double stop_float, double step_float,
    uint8_t start_tag, uint8_t stop_tag, uint8_t step_tag,
    uint8_t has_stop, uint8_t dtype_code);
extern lean_object* tgrad_dtype_table_query_lean(
    uint8_t table, uint8_t query, size_t row, size_t column);
extern lean_object* tgrad_dtype_table_name_lean(uint8_t table, size_t row);
extern lean_object* tgrad_bf16_pack_bytes_lean(lean_object* bytes);
extern lean_object* tgrad_bf16_expand_bytes_lean(lean_object* bytes);
extern lean_object* tgrad_bf16_round_bits_lean(uint32_t bits);
extern lean_object* tgrad_low_precision_scalar_lean(
    uint8_t operation, uint8_t dtype_code, uint64_t input, uint8_t query);
extern lean_object* tgrad_low_precision_decode_public_lean(
    lean_object* payload, uint8_t payload_tag, uint8_t dtype_code, uint8_t query);
extern lean_object* tgrad_low_precision_value_public_lean(
    uint8_t operation, uint8_t dtype_code, uint64_t input,
    uint8_t value_tag, uint8_t query);
extern lean_object* tgrad_tensor_cast_lean(uint64_t source, uint8_t target);
extern lean_object* tgrad_tensor_bitcast_lean(uint64_t source, uint8_t target);
extern lean_object* tgrad_tensor_transform_query_lean(uint64_t handle, uint8_t query);
extern lean_object* tgrad_tensor_transform_release_lean(uint64_t handle);
extern lean_object* tgrad_tensor_registry_count_lean(void);
extern lean_object* tgrad_tensor_is_materialized_storage_lean(uint64_t handle);

extern void theograd_metal_counter_reset(void);
extern uint64_t theograd_metal_counter(uint8_t index);
extern void theograd_metal_fault_set(uint8_t kind);
extern void theograd_metal_fault_clear(void);
extern void theograd_metal_watch_buffer(void* ptr);
extern uint64_t theograd_metal_watch_free_count(void);

static int g_initialized = 0;

/* Initialize Lean's runtime + the Tgrad module. Must be called once
 * before any other tgrad_* function. Returns 0 on success, -1 on init
 * error. Subsequent calls are no-ops. */
int tgrad_init(void) {
    if (g_initialized) return 0;
    /* Mirror Lake's executable main() wrapper. lean_initialize() sets
     * up the GC / object pool / IO runtime; init_task_manager is
     * required for blocking IO ops (readFile, etc.) to schedule
     * correctly. Skip either of these and IO operations crash inside
     * lean_dec_ref_cold on the IO world's task state. */
    lean_initialize();
    lean_set_panic_messages(false);
    lean_object* res = initialize_tgrad_Tgrad(1);
    lean_set_panic_messages(true);
    if (lean_io_result_is_error(res)) {
        lean_dec_ref(res);
        return -1;
    }
    lean_dec_ref(res);
    lean_io_mark_end_initialization();
    lean_init_task_manager();
    g_initialized = 1;
    return 0;
}

/* Refcount exposers — Lean's lean_inc_ref / lean_dec_ref are static
 * inline in lean.h, so Python's ctypes can't reach them. Expose as real
 * symbols for Python's `weakref.finalize` lifecycle. (For the matmul
 * surface we don't currently hand Python opaque Lean structures, but
 * keeping these here makes the dylib spec-complete per §G6.b.) */
void tgrad_handle_inc(void* h) {
    if (h) lean_inc_ref((lean_object*)h);
}

void tgrad_handle_dec(void* h) {
    if (h) lean_dec_ref((lean_object*)h);
}

/* uint64_t tgrad_tensor_alloc(size_t n_bytes)
 * Returns the raw MTLBuffer pointer as uint64_t; 0 on failure. */
uint64_t tgrad_tensor_alloc(size_t n_bytes) {
    lean_object* result = tgrad_tensor_alloc_lean(n_bytes);
    if (lean_io_result_is_error(result)) {
        lean_dec_ref(result);
        return 0;
    }
    uint64_t v = lean_unbox_uint64(lean_io_result_get_value(result));
    lean_dec_ref(result);
    return v;
}

/* void tgrad_tensor_free(uint64_t buf_ptr, size_t n_bytes)
 * Returns the buffer to the LRU pool. */
void tgrad_tensor_free(uint64_t buf_ptr, size_t n_bytes) {
    lean_object* result = tgrad_tensor_free_lean(buf_ptr, n_bytes);
    lean_dec_ref(result);
}

/* int tgrad_tensor_write_bytes(uint64_t buf_ptr, const uint8_t* src, size_t n_bytes)
 * Copies `n_bytes` from `src` into the buffer at offset 0.
 * Returns 0 on success, negative on error. */
int tgrad_tensor_write_bytes(uint64_t buf_ptr, const uint8_t* src, size_t n_bytes) {
    if (!src) return -1;
    /* Allocate a Lean ByteArray of `n_bytes`; copy into its data;
     * pass to the @[export] entry which copies again to MTLBuffer
     * contents. (Two host-side copies; acceptable for L6.b — matches
     * the §G_L5_b path.) */
    lean_object* arr = lean_alloc_sarray(1, n_bytes, n_bytes);
    if (!arr) return -2;
    memcpy(lean_sarray_cptr(arr), src, n_bytes);
    lean_object* result = tgrad_tensor_write_bytes_lean(buf_ptr, arr);
    int rc = lean_io_result_is_error(result) ? -3 : 0;
    lean_dec_ref(result);
    return rc;
}

/* int tgrad_tensor_read_bytes(uint64_t buf_ptr, uint8_t* dst, size_t n_bytes)
 * Copies `n_bytes` from the buffer's contents into `dst`.
 * Returns 0 on success, negative on error. */
int tgrad_tensor_read_bytes(uint64_t buf_ptr, uint8_t* dst, size_t n_bytes) {
    if (n_bytes == 0) return 0;
    if (!buf_ptr) return -1;
    if (!dst) return -1;
    lean_object* result = tgrad_tensor_read_bytes_lean(buf_ptr, n_bytes);
    if (lean_io_result_is_error(result)) {
        lean_dec_ref(result);
        return -2;
    }
    lean_object* arr = lean_io_result_get_value(result);   /* borrowed */
    size_t actual = lean_sarray_size(arr);
    if (actual < n_bytes) {
        lean_dec_ref(result);
        return -3;
    }
    memcpy(dst, lean_sarray_cptr(arr), n_bytes);
    lean_dec_ref(result);
    return 0;
}

/* Foreign-grounded dtype metadata/query surface.  Python interprets stable
 * numeric/string answers but never carries its own lattice or rounding rule. */
uint64_t tgrad_dtype_query(uint8_t code, uint8_t query) {
    lean_object* result = tgrad_dtype_query_lean(code, query);
    if (lean_io_result_is_error(result)) { lean_dec_ref(result); return UINT64_MAX; }
    uint64_t value = lean_unbox_uint64(lean_io_result_get_value(result));
    lean_dec_ref(result);
    return value;
}

uint8_t tgrad_dtype_binary_query(uint8_t query, uint8_t left, uint8_t right) {
    lean_object* result = tgrad_dtype_binary_query_lean(query, left, right);
    if (lean_io_result_is_error(result)) { lean_dec_ref(result); return 255; }
    uint8_t value = (uint8_t)lean_unbox(lean_io_result_get_value(result));
    lean_dec_ref(result);
    return value;
}

uint8_t tgrad_dtype_unary_query(uint8_t query, uint8_t code) {
    lean_object* result = tgrad_dtype_unary_query_lean(query, code);
    if (lean_io_result_is_error(result)) { lean_dec_ref(result); return 255; }
    uint8_t value = (uint8_t)lean_unbox(lean_io_result_get_value(result));
    lean_dec_ref(result);
    return value;
}

uint8_t tgrad_dtype_lub_many(const uint8_t* codes, size_t count) {
    if (!codes || count == 0) return 255;
    lean_object* arr = lean_alloc_array(count, count);
    for (size_t i = 0; i < count; i++) {
        lean_array_set_core(arr, i, lean_box((size_t)codes[i]));
    }
    lean_object* result = tgrad_dtype_lub_many_lean(arr);
    if (lean_io_result_is_error(result)) { lean_dec_ref(result); return 255; }
    uint8_t value = (uint8_t)lean_unbox(lean_io_result_get_value(result));
    lean_dec_ref(result);
    return value;
}

uint8_t tgrad_dtype_infer_python(const uint8_t* tags, size_t count) {
    if (!tags && count) return 255;
    lean_object* arr = lean_alloc_array(count, count);
    for (size_t i = 0; i < count; i++) {
        lean_array_set_core(arr, i, lean_box((size_t)tags[i]));
    }
    lean_object* result = tgrad_dtype_infer_python_lean(arr);
    if (lean_io_result_is_error(result)) { lean_dec_ref(result); return 255; }
    uint8_t value = (uint8_t)lean_unbox(lean_io_result_get_value(result));
    lean_dec_ref(result);
    return value;
}

uint8_t tgrad_dtype_default(uint8_t which) {
    lean_object* result = tgrad_dtype_default_lean(which);
    if (lean_io_result_is_error(result)) { lean_dec_ref(result); return 255; }
    uint8_t value = (uint8_t)lean_unbox(lean_io_result_get_value(result));
    lean_dec_ref(result);
    return value;
}

uint8_t tgrad_dtype_set_default(uint8_t which, uint8_t code) {
    lean_object* result = tgrad_dtype_set_default_lean(which, code);
    if (lean_io_result_is_error(result)) { lean_dec_ref(result); return 0; }
    uint8_t value = (uint8_t)lean_unbox(lean_io_result_get_value(result));
    lean_dec_ref(result);
    return value;
}

uint8_t tgrad_dtype_creation_default(void) {
    lean_object* result = tgrad_dtype_creation_default_lean();
    if (lean_io_result_is_error(result)) { lean_dec_ref(result); return 255; }
    uint8_t value = (uint8_t)lean_unbox(lean_io_result_get_value(result));
    lean_dec_ref(result);
    return value;
}

/* Returns the required UTF-8 byte count (excluding NUL). If dst/cap are
 * supplied, copies a NUL-terminated prefix. */
size_t tgrad_dtype_backend_name(uint8_t code, char* dst, size_t cap) {
    lean_object* result = tgrad_dtype_backend_name_lean(code);
    if (lean_io_result_is_error(result)) { lean_dec_ref(result); return 0; }
    lean_object* value = lean_io_result_get_value(result);
    const char* src = lean_string_cstr(value);
    size_t needed = strlen(src);
    if (dst && cap) {
        size_t n = needed < cap - 1 ? needed : cap - 1;
        memcpy(dst, src, n);
        dst[n] = '\0';
    }
    lean_dec_ref(result);
    return needed;
}

size_t tgrad_dtype_public_name(uint8_t code, char* dst, size_t cap) {
    lean_object* result = tgrad_dtype_public_name_lean(code);
    if (lean_io_result_is_error(result)) { lean_dec_ref(result); return 0; }
    const char* src = lean_string_cstr(lean_io_result_get_value(result));
    size_t needed = strlen(src);
    if (dst && cap) {
        size_t n = needed < cap - 1 ? needed : cap - 1;
        memcpy(dst, src, n); dst[n] = '\0';
    }
    lean_dec_ref(result);
    return needed;
}

size_t tgrad_dtype_display_name(uint8_t code, char* dst, size_t cap) {
    lean_object* result = tgrad_dtype_display_name_lean(code);
    if (lean_io_result_is_error(result)) { lean_dec_ref(result); return 0; }
    const char* src = lean_string_cstr(lean_io_result_get_value(result));
    size_t needed = strlen(src);
    if (dst && cap) {
        size_t n = needed < cap - 1 ? needed : cap - 1;
        memcpy(dst, src, n); dst[n] = '\0';
    }
    lean_dec_ref(result);
    return needed;
}

uint64_t tgrad_dtype_table_query(
    uint8_t table, uint8_t query, size_t row, size_t column) {
    lean_object* result = tgrad_dtype_table_query_lean(table, query, row, column);
    if (lean_io_result_is_error(result)) { lean_dec_ref(result); return UINT64_MAX; }
    uint64_t value = lean_unbox_uint64(lean_io_result_get_value(result));
    lean_dec_ref(result);
    return value;
}

size_t tgrad_dtype_table_name(
    uint8_t table, size_t row, char* dst, size_t cap) {
    lean_object* result = tgrad_dtype_table_name_lean(table, row);
    if (lean_io_result_is_error(result)) { lean_dec_ref(result); return 0; }
    const char* src = lean_string_cstr(lean_io_result_get_value(result));
    size_t needed = strlen(src);
    if (dst && cap) {
        size_t n = needed < cap - 1 ? needed : cap - 1;
        memcpy(dst, src, n); dst[n] = '\0';
    }
    lean_dec_ref(result);
    return needed;
}

static int tgrad_convert_bytes(
    lean_object* (*convert)(lean_object*),
    const uint8_t* src, size_t src_bytes, uint8_t* dst, size_t dst_bytes) {
    if ((!src && src_bytes) || (!dst && dst_bytes)) return -1;
    lean_object* input = lean_alloc_sarray(1, src_bytes, src_bytes);
    if (!input) return -2;
    if (src_bytes) memcpy(lean_sarray_cptr(input), src, src_bytes);
    lean_object* result = convert(input);
    if (lean_io_result_is_error(result)) { lean_dec_ref(result); return -3; }
    lean_object* output = lean_io_result_get_value(result);
    size_t actual = lean_sarray_size(output);
    if (actual != dst_bytes) { lean_dec_ref(result); return -4; }
    if (dst_bytes) memcpy(dst, lean_sarray_cptr(output), dst_bytes);
    lean_dec_ref(result);
    return 0;
}

int tgrad_bf16_pack_bytes(
    const uint8_t* src, size_t src_bytes, uint8_t* dst, size_t dst_bytes) {
    if (src_bytes % 4 != 0 || dst_bytes != src_bytes / 2) return -5;
    return tgrad_convert_bytes(tgrad_bf16_pack_bytes_lean, src, src_bytes, dst, dst_bytes);
}

int tgrad_bf16_expand_bytes(
    const uint8_t* src, size_t src_bytes, uint8_t* dst, size_t dst_bytes) {
    if (src_bytes % 2 != 0 || dst_bytes != src_bytes * 2) return -5;
    return tgrad_convert_bytes(tgrad_bf16_expand_bytes_lean, src, src_bytes, dst, dst_bytes);
}

uint32_t tgrad_bf16_round_bits(uint32_t bits) {
    lean_object* result = tgrad_bf16_round_bits_lean(bits);
    if (lean_io_result_is_error(result)) { lean_dec_ref(result); return 0; }
    uint32_t value = lean_unbox_uint32(lean_io_result_get_value(result));
    lean_dec_ref(result);
    return value;
}

uint64_t tgrad_low_precision_scalar(
    uint8_t operation, uint8_t dtype_code, uint64_t input, uint8_t query) {
    lean_object* result = tgrad_low_precision_scalar_lean(
        operation, dtype_code, input, query);
    if (lean_io_result_is_error(result)) {
        lean_dec_ref(result);
        return UINT64_MAX;
    }
    uint64_t value = lean_unbox_uint64(lean_io_result_get_value(result));
    lean_dec_ref(result);
    return value;
}

uint64_t tgrad_low_precision_decode_public(
    const char* payload, uint8_t payload_tag, uint8_t dtype_code, uint8_t query) {
    if (!payload) return UINT64_MAX;
    lean_object* payload_int = lean_cstr_to_int(payload);
    lean_object* result = tgrad_low_precision_decode_public_lean(
        payload_int, payload_tag, dtype_code, query);
    if (lean_io_result_is_error(result)) {
        lean_dec_ref(result);
        return UINT64_MAX;
    }
    uint64_t value = lean_unbox_uint64(lean_io_result_get_value(result));
    lean_dec_ref(result);
    return value;
}

uint64_t tgrad_low_precision_value_public(
    uint8_t operation, uint8_t dtype_code, uint64_t input,
    uint8_t value_tag, uint8_t query) {
    lean_object* result = tgrad_low_precision_value_public_lean(
        operation, dtype_code, input, value_tag, query);
    if (lean_io_result_is_error(result)) {
        lean_dec_ref(result);
        return UINT64_MAX;
    }
    uint64_t value = lean_unbox_uint64(lean_io_result_get_value(result));
    lean_dec_ref(result);
    return value;
}

/* int32_t tgrad_matmul_64x64(uint64_t a, uint64_t b, uint64_t out)
 * Runs the captured bf16 64×64 matmul on (a, b) → out. Returns 0 on
 * success; negative on Pipeline error (-1 MSL missing, -2 empty,
 * -3 compile failed, -1000 IO error, other = signed dispatch rc). */
int32_t tgrad_matmul_64x64(uint64_t a, uint64_t b, uint64_t out) {
    lean_object* result = tgrad_matmul_64x64_lean(a, b, out);
    if (lean_io_result_is_error(result)) {
        lean_dec_ref(result);
        return -1000;
    }
    /* Int32 is bit-equivalent to UInt32; reinterpret. */
    int32_t v = (int32_t)lean_unbox_uint32(lean_io_result_get_value(result));
    lean_dec_ref(result);
    return v;
}

/* Forward decl for the general matmul @[export] entry (PythonFFI.lean
 * line 123 — `tgrad_matmul_lean`). Lean's IO calling convention:
 * returns lean_obj_res wrapping the Int32 result. */
extern lean_object* tgrad_matmul_lean(
    size_t M, size_t K, size_t N,
    uint64_t a, uint64_t b, uint64_t out
);

/* int32_t tgrad_matmul(M, K, N, a, b, out)
 *
 * General bf16 matmul trampoline. The Lean side routes (M, K, N)
 * through `ShapeSentinel.ofTriple` to select the right captured MSL
 * and dispatch dims (per-shape lib-cache amortises compile cost).
 *
 * Return codes (signed; reinterpreted from Lean's Int32):
 *    0   : dispatch succeeded
 *   -1   : (M, K, N) not in the L11 manifest (no captured MSL)
 *   -2   : MSL fixture missing OR metalCompile failed
 *  -1000 : Lean IO error
 *   other: signed dispatch rc passed through from the Metal bridge. */
int32_t tgrad_matmul(size_t M, size_t K, size_t N,
                     uint64_t a, uint64_t b, uint64_t out) {
    lean_object* result = tgrad_matmul_lean(M, K, N, a, b, out);
    if (lean_io_result_is_error(result)) {
        lean_dec_ref(result);
        return -1000;
    }
    int32_t v = (int32_t)lean_unbox_uint32(lean_io_result_get_value(result));
    lean_dec_ref(result);
    return v;
}

/* L12 — alternate generated-emitter entry. Lean-side
 * `tgrad_matmul_alg_lean` compiles the same parametric declaration as
 * production through a separate observable cache. Same return contract as
 * `tgrad_matmul`; no product path reads captured source. */
extern lean_object* tgrad_matmul_alg_lean(
    size_t M, size_t K, size_t N,
    uint64_t a, uint64_t b, uint64_t out
);

int32_t tgrad_matmul_alg(size_t M, size_t K, size_t N,
                         uint64_t a, uint64_t b, uint64_t out) {
    lean_object* result = tgrad_matmul_alg_lean(M, K, N, a, b, out);
    if (lean_io_result_is_error(result)) {
        lean_dec_ref(result);
        return -1000;
    }
    int32_t v = (int32_t)lean_unbox_uint32(lean_io_result_get_value(result));
    lean_dec_ref(result);
    return v;
}

/* L13.B — scalar-matmul entry for below-TC-tile shapes (any dim < 8).
 * Lean-side `tgrad_matmul_small_lean` renders a per-shape scalar
 * kernel from `scalarMatmulKernelDecl(M, K, N)`. Returns -1 if
 * (M, K, N) is NOT a below-TC-tile shape (caller misuse); returns
 * -2 on compile failure; other negative codes mirror dispatch rc. */
extern lean_object* tgrad_matmul_small_lean(
    size_t M, size_t K, size_t N,
    uint64_t a, uint64_t b, uint64_t out
);

int32_t tgrad_matmul_small(size_t M, size_t K, size_t N,
                           uint64_t a, uint64_t b, uint64_t out) {
    lean_object* result = tgrad_matmul_small_lean(M, K, N, a, b, out);
    if (lean_io_result_is_error(result)) {
        lean_dec_ref(result);
        return -1000;
    }
    int32_t v = (int32_t)lean_unbox_uint32(lean_io_result_get_value(result));
    lean_dec_ref(result);
    return v;
}

/* L13.F — TC-general matmul. Routes TC-eligible non-sentinel shapes
 * through Lean's `tcMatmulKernelDecl` (pure on (M, K, N)) → renderKernel
 * → metalCompile → dispatch with the WMMA tile layout. Returns -1 if
 * (M, K, N) is NOT TC-eligible (caller should use scalar/sentinel
 * route); -2 on compile failure. */
extern lean_object* tgrad_matmul_tc_lean(
    size_t M, size_t K, size_t N,
    uint64_t a, uint64_t b, uint64_t out
);

int32_t tgrad_matmul_tc(size_t M, size_t K, size_t N,
                        uint64_t a, uint64_t b, uint64_t out) {
    lean_object* result = tgrad_matmul_tc_lean(M, K, N, a, b, out);
    if (lean_io_result_is_error(result)) {
        lean_dec_ref(result);
        return -1000;
    }
    int32_t v = (int32_t)lean_unbox_uint32(lean_io_result_get_value(result));
    lean_dec_ref(result);
    return v;
}

/* L13.F.STRICT.B — manual-load TC-general matmul. Installed as a
 * separate callable entry until L13.F.STRICT.C flips production
 * routing to this kernel. */
extern lean_object* tgrad_matmul_tc_manual_load_lean(
    size_t M, size_t K, size_t N,
    uint64_t a, uint64_t b, uint64_t out
);

int32_t tgrad_matmul_tc_manual_load(size_t M, size_t K, size_t N,
                                    uint64_t a, uint64_t b, uint64_t out) {
    lean_object* result = tgrad_matmul_tc_manual_load_lean(M, K, N, a, b, out);
    if (lean_io_result_is_error(result)) {
        lean_dec_ref(result);
        return -1000;
    }
    int32_t v = (int32_t)lean_unbox_uint32(lean_io_result_get_value(result));
    lean_dec_ref(result);
    return v;
}

/* L13.F eligibility query. Pure on (M, K, N). Returns 1 if Lean's
 * `tcMatmulKernelDecl` would produce a TC plan for this shape; 0
 * otherwise. Python uses this to route TC vs scalar BEFORE dispatch
 * — the routing decision is Lean's, not Python's. */
extern lean_object* tgrad_matmul_tc_eligible_lean(
    size_t M, size_t K, size_t N
);

int32_t tgrad_matmul_tc_eligible(size_t M, size_t K, size_t N) {
    lean_object* result = tgrad_matmul_tc_eligible_lean(M, K, N);
    if (lean_io_result_is_error(result)) {
        lean_dec_ref(result);
        return 0;
    }
    int32_t v = (int32_t)lean_unbox_uint32(lean_io_result_get_value(result));
    lean_dec_ref(result);
    return v;
}

/* L14.A — Tensor registry (opaque handle → Lean-owned Tensor).
 *
 * `tgrad_tensor_from_buffer` constructs a `Tensor { uop := .buffer h
 * shape dtype, dtype }` and returns the opaque uint64 handle. Python
 * stores the handle and uses it in future view methods (L14.B+) or
 * to look up the underlying buffer / shape (L14.A query entries
 * below).
 *
 * Dtype encoding: 0 = bfloat16, 1 = float32, 2 = float16, 3 = int32.
 */
extern lean_object* tgrad_tensor_from_buffer_lean(
    uint64_t handle, lean_object* shape_arr, uint8_t dtype_code);
extern lean_object* tgrad_tensor_rank_lean(uint64_t h);
extern lean_object* tgrad_tensor_shape_dim_lean(uint64_t h, size_t i);
extern lean_object* tgrad_tensor_raw_buffer_lean(uint64_t h);
extern lean_object* tgrad_tensor_size_bytes_lean(uint64_t h);

uint64_t tgrad_tensor_from_buffer(
    uint64_t handle, const size_t* shape, size_t ndim, uint8_t dtype_code) {
    /* Build a Lean `Array USize` of size `ndim` containing the shape
     * dims. Lean's Array<α> stores boxed elements; for α = USize the
     * elements are produced via lean_box_usize. */
    lean_object* arr = lean_alloc_array(ndim, ndim);
    for (size_t i = 0; i < ndim; i++) {
        lean_array_set_core(arr, i, lean_box_usize(shape ? shape[i] : 0));
    }
    /* lean_array_set_core takes ownership of each element; the array
     * itself is passed to the Lean side which owns + releases it. */
    lean_object* result = tgrad_tensor_from_buffer_lean(handle, arr, dtype_code);
    if (lean_io_result_is_error(result)) {
        lean_dec_ref(result);
        return 0;
    }
    uint64_t v = lean_unbox_uint64(lean_io_result_get_value(result));
    lean_dec_ref(result);
    return v;
}

size_t tgrad_tensor_rank(uint64_t h) {
    lean_object* result = tgrad_tensor_rank_lean(h);
    if (lean_io_result_is_error(result)) {
        lean_dec_ref(result);
        return 0;
    }
    size_t v = lean_unbox_usize(lean_io_result_get_value(result));
    lean_dec_ref(result);
    return v;
}

size_t tgrad_tensor_shape_dim(uint64_t h, size_t i) {
    lean_object* result = tgrad_tensor_shape_dim_lean(h, i);
    if (lean_io_result_is_error(result)) {
        lean_dec_ref(result);
        return 0;
    }
    size_t v = lean_unbox_usize(lean_io_result_get_value(result));
    lean_dec_ref(result);
    return v;
}

uint64_t tgrad_tensor_raw_buffer(uint64_t h) {
    lean_object* result = tgrad_tensor_raw_buffer_lean(h);
    if (lean_io_result_is_error(result)) {
        lean_dec_ref(result);
        return 0;
    }
    uint64_t v = lean_unbox_uint64(lean_io_result_get_value(result));
    lean_dec_ref(result);
    return v;
}

size_t tgrad_tensor_size_bytes(uint64_t h) {
    lean_object* result = tgrad_tensor_size_bytes_lean(h);
    if (lean_io_result_is_error(result)) {
        lean_dec_ref(result);
        return 0;
    }
    size_t v = lean_unbox_usize(lean_io_result_get_value(result));
    lean_dec_ref(result);
    return v;
}

/* L14.B.1 — view-method trampolines. Each composes a movement node on
 * the underlying Tensor's uop and returns a new opaque handle. Pure
 * graph transforms; no buffer allocation, no kernel dispatch. */
extern lean_object* tgrad_tensor_transpose_lean(uint64_t h);
extern lean_object* tgrad_tensor_permute_lean(uint64_t h, lean_object* axes_arr);
extern lean_object* tgrad_tensor_reshape_lean(uint64_t h, lean_object* shape_arr);
extern lean_object* tgrad_tensor_expand_lean(uint64_t h, lean_object* shape_arr);
extern lean_object* tgrad_tensor_slice_lean(uint64_t h, lean_object* slices_flat);
extern lean_object* tgrad_tensor_uop_kind_lean(uint64_t h);

/* Helper: marshal `const size_t* arr` of length `n` into a Lean
 * `Array USize`. Used by permute / reshape / expand / slice. */
static lean_object* tg_alloc_usize_array(const size_t* arr, size_t n) {
    lean_object* a = lean_alloc_array(n, n);
    for (size_t i = 0; i < n; i++) {
        lean_array_set_core(a, i, lean_box_usize(arr ? arr[i] : 0));
    }
    return a;
}

uint64_t tgrad_tensor_transpose(uint64_t h) {
    lean_object* result = tgrad_tensor_transpose_lean(h);
    if (lean_io_result_is_error(result)) {
        lean_dec_ref(result);
        return 0;
    }
    uint64_t v = lean_unbox_uint64(lean_io_result_get_value(result));
    lean_dec_ref(result);
    return v;
}

uint64_t tgrad_tensor_permute(uint64_t h, const size_t* axes, size_t n) {
    lean_object* a = tg_alloc_usize_array(axes, n);
    lean_object* result = tgrad_tensor_permute_lean(h, a);
    if (lean_io_result_is_error(result)) {
        lean_dec_ref(result);
        return 0;
    }
    uint64_t v = lean_unbox_uint64(lean_io_result_get_value(result));
    lean_dec_ref(result);
    return v;
}

uint64_t tgrad_tensor_reshape(uint64_t h, const size_t* shape, size_t n) {
    lean_object* a = tg_alloc_usize_array(shape, n);
    lean_object* result = tgrad_tensor_reshape_lean(h, a);
    if (lean_io_result_is_error(result)) {
        lean_dec_ref(result);
        return 0;
    }
    uint64_t v = lean_unbox_uint64(lean_io_result_get_value(result));
    lean_dec_ref(result);
    return v;
}

uint64_t tgrad_tensor_expand(uint64_t h, const size_t* shape, size_t n) {
    lean_object* a = tg_alloc_usize_array(shape, n);
    lean_object* result = tgrad_tensor_expand_lean(h, a);
    if (lean_io_result_is_error(result)) {
        lean_dec_ref(result);
        return 0;
    }
    uint64_t v = lean_unbox_uint64(lean_io_result_get_value(result));
    lean_dec_ref(result);
    return v;
}

/* `slices_flat` is a flat array of `3 * ndim` size_t entries:
 * [start_0, stop_0, step_0, start_1, stop_1, step_1, ...]. */
uint64_t tgrad_tensor_slice(uint64_t h, const size_t* slices_flat, size_t flat_len) {
    lean_object* a = tg_alloc_usize_array(slices_flat, flat_len);
    lean_object* result = tgrad_tensor_slice_lean(h, a);
    if (lean_io_result_is_error(result)) {
        lean_dec_ref(result);
        return 0;
    }
    uint64_t v = lean_unbox_uint64(lean_io_result_get_value(result));
    lean_dec_ref(result);
    return v;
}

/* Returns 0=BUFFER, 1=PERMUTE, 2=RESHAPE, 3=EXPAND, 4=SLICE,
 * 255=other/unregistered. */
uint8_t tgrad_tensor_uop_kind(uint64_t h) {
    lean_object* result = tgrad_tensor_uop_kind_lean(h);
    if (lean_io_result_is_error(result)) {
        lean_dec_ref(result);
        return 255;
    }
    uint8_t v = lean_unbox(lean_io_result_get_value(result));
    lean_dec_ref(result);
    return v;
}

/* L14.B.2.c: view-aware matmul. Called by Python __matmul__ when
 * either input has a non-BUFFER uop. Returns the new tensor handle
 * (with BUFFER root) for the output; 0 on error. */
extern lean_object* tgrad_matmul_view_lean(uint64_t a_handle, uint64_t b_handle);

uint64_t tgrad_matmul_view(uint64_t a_handle, uint64_t b_handle) {
    lean_object* result = tgrad_matmul_view_lean(a_handle, b_handle);
    if (lean_io_result_is_error(result)) {
        lean_dec_ref(result);
        return 0;
    }
    uint64_t v = lean_unbox_uint64(lean_io_result_get_value(result));
    lean_dec_ref(result);
    return v;
}

/* Graph-indexed realize. These three replace per-op FFI growth: Tensor
 * methods compose a UOp graph, and one entry lowers it. Signatures match
 * .lake/build/ir/Tgrad/PythonFFI.c exactly. */
extern lean_object* tgrad_tensor_binop_lean(uint8_t op, uint64_t h1, uint64_t h2);
extern lean_object* tgrad_tensor_reduce_lean(uint8_t op, uint64_t h, size_t axis);
extern lean_object* tgrad_realize_lean(uint64_t h);

static uint64_t tgrad_unbox_handle(lean_object* result) {
    if (lean_io_result_is_error(result)) {
        lean_dec_ref(result);
        return 0;
    }
    uint64_t v = lean_unbox_uint64(lean_io_result_get_value(result));
    lean_dec_ref(result);
    return v;
}

uint64_t tgrad_tensor_binop(uint8_t op, uint64_t h1, uint64_t h2) {
    return tgrad_unbox_handle(tgrad_tensor_binop_lean(op, h1, h2));
}

uint64_t tgrad_tensor_reduce(uint8_t op, uint64_t h, size_t axis) {
    return tgrad_unbox_handle(tgrad_tensor_reduce_lean(op, h, axis));
}

uint64_t tgrad_realize(uint64_t h) {
    return tgrad_unbox_handle(tgrad_realize_lean(h));
}

extern lean_object* tgrad_tensor_dtype_lean(uint64_t h);

uint8_t tgrad_tensor_dtype(uint64_t h) {
    lean_object* result = tgrad_tensor_dtype_lean(h);
    if (lean_io_result_is_error(result)) { lean_dec_ref(result); return 255; }
    uint8_t v = lean_unbox(lean_io_result_get_value(result));
    lean_dec_ref(result);
    return v;
}

/* Decode one Lean transaction payload `[reason, handle]`.  The status is the
 * Lean-owned reason code; zero-handle conventions do not erase it. */
static uint8_t tgrad_transform_result(
    lean_object* result, uint64_t* out_handle) {
    if (out_handle) *out_handle = 0;
    if (!result || lean_io_result_is_error(result)) {
        if (result) lean_dec_ref(result);
        return 255;
    }
    lean_object* values = lean_io_result_get_value(result);
    if (lean_array_size(values) != 2) {
        lean_dec_ref(result);
        return 255;
    }
    uint8_t status = (uint8_t)lean_unbox_uint64(lean_array_get_core(values, 0));
    uint64_t handle = lean_unbox_uint64(lean_array_get_core(values, 1));
    if (out_handle) *out_handle = handle;
    lean_dec_ref(result);
    return status;
}

uint8_t tgrad_tensor_cast(
    uint64_t source, uint8_t target, uint64_t* out_handle) {
    return tgrad_transform_result(
        tgrad_tensor_cast_lean(source, target), out_handle);
}

uint8_t tgrad_tensor_bitcast(
    uint64_t source, uint8_t target, uint64_t* out_handle) {
    return tgrad_transform_result(
        tgrad_tensor_bitcast_lean(source, target), out_handle);
}

uint64_t tgrad_tensor_transform_query(uint64_t handle, uint8_t query) {
    lean_object* result = tgrad_tensor_transform_query_lean(handle, query);
    if (lean_io_result_is_error(result)) { lean_dec_ref(result); return UINT64_MAX; }
    uint64_t value = lean_unbox_uint64(lean_io_result_get_value(result));
    lean_dec_ref(result);
    return value;
}

uint8_t tgrad_tensor_transform_release(uint64_t handle) {
    lean_object* result = tgrad_tensor_transform_release_lean(handle);
    if (lean_io_result_is_error(result)) { lean_dec_ref(result); return 255; }
    uint8_t status = (uint8_t)lean_unbox(lean_io_result_get_value(result));
    lean_dec_ref(result);
    return status;
}

size_t tgrad_tensor_registry_count(void) {
    lean_object* result = tgrad_tensor_registry_count_lean();
    if (lean_io_result_is_error(result)) { lean_dec_ref(result); return SIZE_MAX; }
    size_t count = lean_unbox_usize(lean_io_result_get_value(result));
    lean_dec_ref(result);
    return count;
}

uint8_t tgrad_tensor_is_materialized_storage(uint64_t handle) {
    lean_object* result = tgrad_tensor_is_materialized_storage_lean(handle);
    if (lean_io_result_is_error(result)) { lean_dec_ref(result); return 255; }
    uint8_t value = (uint8_t)lean_unbox(lean_io_result_get_value(result));
    lean_dec_ref(result);
    return value;
}

void tgrad_metal_counter_reset(void) { theograd_metal_counter_reset(); }
uint64_t tgrad_metal_counter(uint8_t index) { return theograd_metal_counter(index); }
void tgrad_metal_fault_set(uint8_t kind) { theograd_metal_fault_set(kind); }
void tgrad_metal_fault_clear(void) { theograd_metal_fault_clear(); }
void tgrad_metal_watch_buffer(uint64_t ptr) {
    theograd_metal_watch_buffer((void*)(uintptr_t)ptr);
}
uint64_t tgrad_metal_watch_free_count(void) {
    return theograd_metal_watch_free_count();
}

/* Constant-fill creation. Signed dimensions remain signed until Lean has
 * classified them. Lean then owns dtype default/admission, GPU allocation,
 * fill-kernel dispatch, and registry insert. */
extern lean_object* tgrad_tensor_full_lean(
    lean_object* shape_arr, double fill, uint8_t fill_tag, uint8_t dtype_code);

static lean_object* tg_alloc_int64_array(const int64_t* values, size_t count) {
    lean_object* arr = lean_alloc_array(count, count);
    for (size_t i = 0; i < count; i++) {
        lean_array_set_core(
            arr, i, lean_int64_to_int(values ? values[i] : 0));
    }
    return arr;
}

uint8_t tgrad_creation_shape_admission(
    const int64_t* shape, size_t ndim) {
    if (!shape && ndim) return 255;
    lean_object* result = tgrad_creation_shape_admission_lean(
        tg_alloc_int64_array(shape, ndim));
    if (lean_io_result_is_error(result)) {
        lean_dec_ref(result);
        return 255;
    }
    uint8_t value = (uint8_t)lean_unbox(lean_io_result_get_value(result));
    lean_dec_ref(result);
    return value;
}

uint8_t tgrad_creation_dtype_resolve(uint8_t fill_tag, uint8_t dtype_code) {
    lean_object* result = tgrad_creation_dtype_resolve_lean(
        fill_tag, dtype_code);
    if (lean_io_result_is_error(result)) {
        lean_dec_ref(result);
        return 255;
    }
    uint8_t value = (uint8_t)lean_unbox(lean_io_result_get_value(result));
    lean_dec_ref(result);
    return value;
}

uint64_t tgrad_tensor_full(
    const int64_t* shape, size_t ndim, double fill,
    uint8_t fill_tag, uint8_t dtype_code) {
    if (!shape && ndim) return 0;
    return tgrad_unbox_handle(tgrad_tensor_full_lean(
        tg_alloc_int64_array(shape, ndim), fill, fill_tag, dtype_code));
}

uint64_t tgrad_full_like_query(
    uint64_t source_handle, uint8_t fill_tag, uint8_t dtype_code,
    uint8_t query, size_t index) {
    lean_object* result = tgrad_full_like_query_lean(
        source_handle, fill_tag, dtype_code, query, index);
    if (lean_io_result_is_error(result)) {
        lean_dec_ref(result);
        return UINT64_MAX;
    }
    uint64_t value = lean_unbox_uint64(lean_io_result_get_value(result));
    lean_dec_ref(result);
    return value;
}

uint64_t tgrad_tensor_full_like(
    uint64_t source_handle, double fill, uint8_t fill_tag,
    uint8_t dtype_code) {
    return tgrad_unbox_handle(tgrad_tensor_full_like_lean(
        source_handle, fill, fill_tag, dtype_code));
}

uint64_t tgrad_range_query(
    const char* start_int, const char* stop_int, const char* step_int,
    double start_float, double stop_float, double step_float,
    uint8_t start_tag, uint8_t stop_tag, uint8_t step_tag,
    uint8_t has_stop, uint8_t dtype_code, uint8_t query, size_t index) {
    if (!start_int || !stop_int || !step_int) return UINT64_MAX;
    /* The generated export transfers these objects into owned constructors
       and consumes them; a caller-side lean_dec would double-decrement. */
    lean_object* tgrad_range_query_start_int = lean_cstr_to_int(start_int);
    lean_object* tgrad_range_query_stop_int = lean_cstr_to_int(stop_int);
    lean_object* tgrad_range_query_step_int = lean_cstr_to_int(step_int);
    lean_object* result = tgrad_range_query_lean(
        tgrad_range_query_start_int, tgrad_range_query_stop_int,
        tgrad_range_query_step_int, start_float, stop_float, step_float,
        start_tag, stop_tag, step_tag, has_stop, dtype_code, query, index);
    if (lean_io_result_is_error(result)) {
        lean_dec_ref(result);
        return UINT64_MAX;
    }
    uint64_t value = lean_unbox_uint64(lean_io_result_get_value(result));
    lean_dec_ref(result);
    return value;
}

uint64_t tgrad_tensor_arange(
    const char* start_int, const char* stop_int, const char* step_int,
    double start_float, double stop_float, double step_float,
    uint8_t start_tag, uint8_t stop_tag, uint8_t step_tag,
    uint8_t has_stop, uint8_t dtype_code) {
    if (!start_int || !stop_int || !step_int) return 0;
    /* See tgrad_range_query: the generated export consumes all three Ints. */
    lean_object* tgrad_tensor_arange_start_int = lean_cstr_to_int(start_int);
    lean_object* tgrad_tensor_arange_stop_int = lean_cstr_to_int(stop_int);
    lean_object* tgrad_tensor_arange_step_int = lean_cstr_to_int(step_int);
    lean_object* result = tgrad_tensor_arange_lean(
        tgrad_tensor_arange_start_int, tgrad_tensor_arange_stop_int,
        tgrad_tensor_arange_step_int, start_float, stop_float, step_float,
        start_tag, stop_tag, step_tag, has_stop, dtype_code);
    return tgrad_unbox_handle(result);
}
