import Tgrad.Growth.BroadcastAddManifestGenerated

/- GENERATED by scripts/spec/generate_broadcast_add_amendment_v2.py; do not edit. -/

namespace Tgrad.Growth.BroadcastAddManifestV2Generated

def trialId : String := "TRIAL-BROADCAST-ADD-PROSPECTIVE-V2"
def packetId : String := "WORK-SPEC-BROADCAST-ADD-PROSPECTIVE-V2"
def baselineRevision : String := "9ab1fcbaecc963d35016eb2cdb36d0c344526129"
def amendmentPath : String := "fixtures/requirements/broadcast_add_prospective_v2_amendment.json"
def amendmentHash : String := "3cd3b5f4534092c008c22c8ef79c481d1c9753831ada848b06b7a82a0362303f"
def baseManifestHash : String := "a0485899ccae42c6378bb96f1fafec802c73c31aa34d956fda9b7f7deb9ec2e9"
def supersededLockHash : String := "77c698ac2ac1e077a6c32ceeb8189a58fa8e9e85a12e28496c6b4a00575b9c8f"
def effectiveManifestHash : String := "0a8cc4f19fdd1177e93e44f93115c6149ea124132380de45eb9c43f64ac57795"
def amendedMutationIds : List String := ["MUT-ADD-WRONG-RIGHT-ALIGNMENT", "MUT-ADD-NO-SINGLETON-EXPANSION"]

theorem amendment_has_exactly_two_mutations : amendedMutationIds.length = 2 := by decide

end Tgrad.Growth.BroadcastAddManifestV2Generated
