import Tgrad.Growth.BroadcastAddManifestV2

/- GENERATED by scripts/spec/generate_broadcast_add_amendment_v3.py; do not edit. -/

namespace Tgrad.Growth.BroadcastAddManifestV3Generated

structure TraceFootprintAmendment where
  mutationId : String
  before : List String
  after : List String
  deriving DecidableEq, BEq, Repr, Inhabited

def trialId : String := "TRIAL-BROADCAST-ADD-PROSPECTIVE-V3"
def packetId : String := "WORK-SPEC-BROADCAST-ADD-PROSPECTIVE-V3"
def baselineRevision : String := "aac178ff1eebf299075f0adce593328380dfa02a"
def amendmentPath : String := "fixtures/requirements/broadcast_add_prospective_v3_amendment.json"
def amendmentHash : String := "e8c78e7ea3d233334bf8fbc752dfeedc6908e86612e244659fca490403a33b0d"
def baseV2LockHash : String := "c52fbd1523fb2a57b613181ac68dcdd183af477ed2737848ba6dce41aeb898ef"
def v2ObserverHash : String := "dd9e74669a6ca010dff427399cb7b064da614892033386aab48883548a561ee1"
def refutingEvidenceId : String := "cd5cab1b0b5e3630f18da2829e87e67b6634e4bd6cbe237733fc70e2dd180f34"
def effectiveContractHash : String := "92ae7cca5e6be6751b242439e600766d75a71c6aab1a3f9dcd838791f634539d"
def traceAmendments : List TraceFootprintAmendment := [
  { mutationId := "MUT-ADD-WRONG-RIGHT-ALIGNMENT", before := ["invoke_add", "capture_result_identity", "observe_shape", "observe_dtype", "realize_1", "readback_1", "realize_2", "readback_2", "snapshot_inputs_after"], after := ["observe_shape", "observe_dtype", "realize_1", "readback_1", "realize_2", "readback_2", "snapshot_inputs_after"] },
  { mutationId := "MUT-ADD-ACCEPT-INCOMPATIBLE", before := ["invoke_add", "observe_shape_if_constructed"], after := ["observe_shape_if_constructed"] }]

theorem amendment_has_exactly_two_trace_corrections : traceAmendments.length = 2 := by decide

end Tgrad.Growth.BroadcastAddManifestV3Generated
