import Tgrad.Evidence.Observations
import Tgrad.Requirements.Pilot
import Tgrad.Specification.Pilot

/- GENERATED by scripts/spec/observe_pilot.py; do not hand edit. -/

namespace Tgrad.Evidence.PilotGenerated

open Tgrad.Requirements
open Tgrad.Requirements.Pilot
open Tgrad.Specification.Pilot
open Tgrad.Evidence

def targetRevision : String := "19c4d736f2bc8e26d21f08b28ffd6298408da00f"
def artifactHash : String := "1014d687ede1cb938fcb2f98398f1916e0f78a456e510a357395ba6b8e31267b"

def subjectTree : TreeRef :=
  { revision := "c465f89999adf0c5fa91d771d3485428d26a2c61"
    contentHash := "c259d0beaa09807c05071608646caa783b021c28"
    dirty := false }

def boundary : BoundaryIdentity :=
  { verifierTree :=
      { revision := "observe-pilot-v1"
        contentHash := "86936c14a188a69c1a327c41c14428b0c4fdd79f49840f786b3db30bdd0ae23e"
        dirty := false }
    adapterHash := "ed6ecc1ff958ea7553e3d4198e16c3cf432eeeb0e8c4d864bce6a3a0200362df"
    environmentId := "python-import-pilot-v1"
    environmentHash := "a9bfa2e8fbcfc22b5020350d8c7f4096ee6a88215c88fea59d1d7b8ffc8608b9"
    scenarioManifestHash := "5570de9a305eade4a4bebb02c280fba5c51dd5abe02d60d4ae9b14ceadc37186" }

def helperValidator : ValidatorRef :=
  { id := "VALIDATOR-HELPERS-IMPORT-V1"
    version := "1"
    dimensions := importHelpers.relation.dimensions
    calibrations :=
      [{ faultModel := "strict shim appends a same-named upstream package path"
         mutantTree := "dded1bf38e8f43ce9f3f2a6d3aeb54616221318ceec301666461849d99451967"
         artifactHash := "1b48490319daeef65cb44cb5b3239e0c79aa0422947182e7787e05ae54480865"
         outcome := .validatorRejectedMutant }] }

def helperObservation : Observation :=
  { id := "OBS-HELPERS-IMPORT-C465F89"
    requirement := importHelpers.id
    specification := helpersBoundary.id
    targetRevision := targetRevision
    subjectTree := subjectTree
    boundary := boundary
    validatorId := helperValidator.id
    dimensions := importHelpers.relation.dimensions
    outcome := .failed
    blocker := ""
    artifactHash := artifactHash
    runId := "5507cd03599dbcad2d1692d997dfc26010b7d17fac540cb19776155b156518cf" }

def validators : List ValidatorRef := [helperValidator]
def observations : List Observation := [helperObservation]


def helpersBlockage : Blockage :=
  { id := "BLOCKAGE-HELPERS-PREREQUISITE"
    blocks := [broadcastAdd.id, viewReadbackLifetime.id]
    targetRevision := targetRevision
    subjectTree := subjectTree
    boundary := boundary
    sourceObservationId := helperObservation.id
    reason := "The strict substitution cannot resolve tinygrad.helpers, so dependent upstream scenarios cannot reach tensor behavior."
    artifactHash := artifactHash }

def blockages : List Blockage := [helpersBlockage]

end Tgrad.Evidence.PilotGenerated
